--- a/.github/workflows/ci-e2e-badger.yaml
+++ b/.github/workflows/ci-e2e-badger.yaml
@@ -48,4 +48,4 @@
       uses: ./.github/actions/upload-codecov
       with:
         files: cover.out
-        flags: badger_${{ matrix.version }}
+        flags: badger_${{ matrix.version }}